# Build and deploy a static preview of a Hyde site using the triggering commit's assets
name: Build and Deploy Preview

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: # todo compile scss and ts files
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
        
      - name: Download base HTML
        run: wget https://raw.githubusercontent.com/caendesilva/hydefront-preview/ce593247034d3fb893537a1e639474c5dfc56720/hydefront-preview.html
        
      - name: Download compiler
        run: wget https://raw.githubusercontent.com/caendesilva/hydefront-preview/4aaa498f341fca0b32df37e20b8f3dd6a0dbeefd/compiler.php

      - name: Run the compiler
        run: php compiler.php ${{ github.sha }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: "output"
          path: "hydefront-preview-output.html"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: hydefront-preview
      url: https://hydephp.github.io/developer-tools/hydefront-previews/${{ github.sha }}

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: "output"
      
      - name: Rename file to index.html
        run: mv hydefront-preview-output.html index.html

      - name: Upload files to GitHub Pages
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "."
          destination-github-username: "hydephp"
          destination-repository-name: "developer-tools"
          target-branch: gh-pages
          target-directory: "hydefront-previews/${{ github.sha }}"

      - name: Output the URL
        run: echo "https://hydephp.github.io/developer-tools/hydefront-previews/${{ github.sha }}"

  report-status:
    needs: deploy
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'A live preview has been deployed at: https://hydephp.github.io/developer-tools/hydefront-previews/${{ github.sha }}!
              
              Please note that it may take a few seconds for GitHub Pages to build and deploy. The preview will be removed in a few days.'
            })