name: Build and Deploy Preview

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: # todo compile scss and ts files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo commit SHA
        run: echo ${{ github.sha }}
      - run: mkdir build
        
        