# Build and deploy a static preview of a Hyde site using the triggering commit's assets
name: Build and Deploy Preview

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: # todo compile scss and ts files
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      
      - name: Get short SHA
        id: short-sha
        run: echo '::set-output name=SHORT_SHA::$(echo ${{ github.sha }} | cut -c -7 )'

      - name: Echo commit SHA
        run: echo ${{ github.sha }} / ${{ steps.short-sha.outputs.SHORT_SHA }}

      # Todo pin the downloads to specific commit sha once stable
      - name: Download base HTML
        run: wget https://raw.githubusercontent.com/caendesilva/hydefront-preview/master/hydefront-preview.html
        
      - name: Download compiler
        run: wget https://raw.githubusercontent.com/caendesilva/hydefront-preview/master/compiler.php

      - name: Run the compiler
        run: php compiler.php ${{ github.sha }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: "output"
          path: "hydefront-preview-output.html"
